### ISSUE TITLE
 Cannot connect to host api.bums.bot:443 ssl:default [None]

### ISSUE THREAD

**Issue by bscongluanbui** [m3taphor/Bums#14]
Hi I got a problem with connection. It can ping the proxy but cannot connect to bums api
"Unknown error when processing request: Cannot connect to host api.bums.bot:443 ssl:default [None]"

**Comment by m3taphor** [comment]
this error can be occur with Proxy or HTTP Intercepting software like BurpSuite or HTTP Debugger
