### ISSUE TITLE
loguru

### ISSUE THREAD

**Issue by damondiamond** [m3taphor/Bums#2]
![image](https://github.com/user-attachments/assets/c3593d3a-f466-42b6-a907-859680c00fd5)
![image](https://github.com/user-attachments/assets/b3648bc0-d91e-423b-93f2-d0c7e2d17a1e)

**Comment by wuwku6e6** [comment]
> ![image](https://private-user-images.githubusercontent.com/21344650/387637967-c3593d3a-f466-42b6-a907-859680c00fd5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwMTg2MDgsIm5iZiI6MTczMjAxODMwOCwicGF0aCI6Ii8yMTM0NDY1MC8zODc2Mzc5NjctYzM1OTNkM2EtZjQ2Ni00MmI2LWE5MDctODU5NjgwYzAwZmQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE5VDEyMTE0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBjYWVlNTNhYzljYTY4Y2UyMWUyYzhhZmU2MmUwZjU4MTE2OWU5YTY4N2NhNGJlOWZmODM3MGVkZGFhMTM3MjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.yScJA0EG5L-KD3ILk6u7Pu3JbGfw1FwfsWicTjycYMY) ![image](https://private-user-images.githubusercontent.com/21344650/387638079-b3648bc0-d91e-423b-93f2-d0c7e2d17a1e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwMTg2MDgsIm5iZiI6MTczMjAxODMwOCwicGF0aCI6Ii8yMTM0NDY1MC8zODc2MzgwNzktYjM2NDhiYzAtZDkxZS00MjNiLTkzZjItZDBjN2UyZDE3YTFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE5VDEyMTE0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI4NGIyYzg5ZWZiYTVjNjQzZDFmNWI1NzM5N2E2ZDQwZTUwYmVkNjdkOGJjMTY0ZDAzYTJlYzk1ZjI5YWRiODEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.jIg7l1bALaAt-n6jmXsxs4m6h83uXy-hwsuF0VzVi_0)

Only Python 3.10 work

**Comment by damondiamond** [comment]
> > ![image](https://private-user-images.githubusercontent.com/21344650/387637967-c3593d3a-f466-42b6-a907-859680c00fd5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwMTg2MDgsIm5iZiI6MTczMjAxODMwOCwicGF0aCI6Ii8yMTM0NDY1MC8zODc2Mzc5NjctYzM1OTNkM2EtZjQ2Ni00MmI2LWE5MDctODU5NjgwYzAwZmQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE5VDEyMTE0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBjYWVlNTNhYzljYTY4Y2UyMWUyYzhhZmU2MmUwZjU4MTE2OWU5YTY4N2NhNGJlOWZmODM3MGVkZGFhMTM3MjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.yScJA0EG5L-KD3ILk6u7Pu3JbGfw1FwfsWicTjycYMY) ![image](https://private-user-images.githubusercontent.com/21344650/387638079-b3648bc0-d91e-423b-93f2-d0c7e2d17a1e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwMTg2MDgsIm5iZiI6MTczMjAxODMwOCwicGF0aCI6Ii8yMTM0NDY1MC8zODc2MzgwNzktYjM2NDhiYzAtZDkxZS00MjNiLTkzZjItZDBjN2UyZDE3YTFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE5VDEyMTE0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI4NGIyYzg5ZWZiYTVjNjQzZDFmNWI1NzM5N2E2ZDQwZTUwYmVkNjdkOGJjMTY0ZDAzYTJlYzk1ZjI5YWRiODEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.jIg7l1bALaAt-n6jmXsxs4m6h83uXy-hwsuF0VzVi_0)
> 
> Only Python 3.10 work

See second screen

**Comment by damondiamond** [comment]
> ![error](https://private-user-images.githubusercontent.com/3669340/387699714-ebb2ba0f-407f-4be0-a7f0-2b9ac0beb0ae.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwMzc0ODgsIm5iZiI6MTczMjAzNzE4OCwicGF0aCI6Ii8zNjY5MzQwLzM4NzY5OTcxNC1lYmIyYmEwZi00MDdmLTRiZTAtYTdmMC0yYjlhYzBiZWIwYWUuUE5HP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTExOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMTlUMTcyNjI4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODM5MjM3OGU3ZTE0OWI0YzNhYzIwZmRkMTgwZDBlMzg5MDJkZTY4OWVlOTZjOWEzZDZmYmEzNTU1MDgyMzkyOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.igvPmf2UTS7-3d4Q8RCaBgE1ly9GEepbgoyKe36AwEI) Eror bro? what can i do?

copy /venv/lib/site-packages from another project and paste in a similar path in this project
