### ISSUE TITLE
Upgrade info

### ISSUE THREAD

**Issue by AntiWarforever** [m3taphor/Bums#20]
Thanks for bot, but see this
Seems just a card upgrade each round
I have 16000000 coin and cards upgrade costs 60k
But don't upgrading...
We are far behind
Add more settings to speed up upgrading cards please
![Screenshot_2024-12-15-02-02-35-800_com polestar super clone-edit](https://github.com/user-attachments/assets/b8363241-74b7-4a45-b89e-bd1e303fb286)

**Comment by m3taphor** [comment]
did you update ENV?

**Comment by AntiWarforever** [comment]
Yes
Upgrade card is true
Max price is 10000000

**Comment by AntiWarforever** [comment]
I check it,in your new update then tell you more about that

**Comment by m3taphor** [comment]
is that working properly?

**Comment by AntiWarforever** [comment]
> is that working properly?

yes work correct thanks
