### ISSUE TITLE
Error while collecting Task-List

### ISSUE THREAD

**Issue by Insomnia731** [m3taphor/Bums#3]
Tap works fine, but there is a problem with tasks:

_BUMS | 2024-11-21 11:34:35 | INFO     | 536 - se | Checking available task...
BUMS | 2024-11-21 11:34:35 | ERROR    | 248 - se | Unknown error when processing request: 500, message='Internal Server Error', url='https://api.bums.bot/miniapps/api/task/lists'
BUMS | 2024-11-21 11:34:37 | ERROR    | 540 - se | Unknown error while collecting Task-List!
BUMS | 2024-11-21 11:34:37 | INFO     | 541 - se | Sleep 66.5 min_

**Comment by m3taphor** [comment]
Are you using proxy?

**Comment by Insomnia731** [comment]
> Are you using proxy?

No

**Comment by m3taphor** [comment]
can be a temporary issue, you won't get permanent
