### ISSUE TITLE
Malicious

### ISSUE THREAD

**Issue by Aphotia1** [m3taphor/Bums#6]
This script is malicious be careful the owner will hack your telegram account

**Comment by m3taphor** [comment]
The script is **open source**, so you can review the code yourself. I have no intention of hacking anyone's Telegram account; I only use referrals as my payment _(which can be turned off by SUPPORT_AUTHOR = False)_, nothing else. If you believe this is malicious, please provide evidence here, and I will address your concerns.

**Comment by m3taphor** [comment]
reopen the issue, i am closing it because of invalid question
